(cl:defpackage ros_start-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SETVELOCITY"
   "<SETVELOCITY-REQUEST>"
   "SETVELOCITY-REQUEST"
   "<SETVELOCITY-RESPONSE>"
   "SETVELOCITY-RESPONSE"
  ))

