// Generated by gencpp from file ros_start/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_START_MESSAGE_ADDTWOINTS_H
#define ROS_START_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_start/AddTwoIntsRequest.h>
#include <ros_start/AddTwoIntsResponse.h>


namespace ros_start
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_start


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_start::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_start::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_start::AddTwoInts > {
  static const char* value()
  {
    return "ros_start/AddTwoInts";
  }

  static const char* value(const ::ros_start::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_start::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::ros_start::AddTwoInts > 
template<>
struct MD5Sum< ::ros_start::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_start::AddTwoInts >::value();
  }
  static const char* value(const ::ros_start::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_start::AddTwoIntsRequest> should match 
// service_traits::DataType< ::ros_start::AddTwoInts > 
template<>
struct DataType< ::ros_start::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_start::AddTwoInts >::value();
  }
  static const char* value(const ::ros_start::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_start::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::ros_start::AddTwoInts > 
template<>
struct MD5Sum< ::ros_start::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_start::AddTwoInts >::value();
  }
  static const char* value(const ::ros_start::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_start::AddTwoIntsResponse> should match 
// service_traits::DataType< ::ros_start::AddTwoInts > 
template<>
struct DataType< ::ros_start::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_start::AddTwoInts >::value();
  }
  static const char* value(const ::ros_start::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_START_MESSAGE_ADDTWOINTS_H
